name: A workflow to prevent suspension of 60-day inactivity
on:
  schedule:
    - cron: "0 0 * * 1"  # every Monday

jobs:
  keepalive:
    name: Cronjob based github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/keepalive-workflow@v1
